# Generated by Django 3.2.5 on 2021-07-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nomlanishi')),
                ('anons', models.CharField(max_length=250, verbose_name='Anons')),
                ('full_test', models.TextField(verbose_name='Maqola')),
                ('data', models.DateTimeField(verbose_name='Habar sanasi')),
            ],
        ),
    ]
